version: "3"

services:

  app:
    build:
      context: .
    container_name: 13ed-api-vagas
    # command: npm run dev
    ports:
      - 8080:8080
      - 9229:9229
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - DATABASE_URL=postgres://growdev:growdev2022@db:5432/growbase
      - TEST_DATABASE_URL=postgres://test:test2022@db_test:5432/test_app
      - REDIS_URL=redis://default:growdev2022@redis:6379
      - USING_DOCKER=true
      - JWT_SECRET=any_pp
      - JWT_EXPIREIN=1h
      - BCRYPT_SALT=8
      - NODE_ENV=development
    networks:
      - growbase
    tty: true
    depends_on:
      - db
      - db_test
      - redis

  db:
    image: postgres:13
    container_name: 13ed-db
    environment:
      POSTGRES_PASSWORD: growdev2022
      POSTGRES_USER: growdev
      POSTGRES_DB: growbase
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - growbase

  db_test:
    image: postgres:13
    container_name: 13ed-db-test
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      POSTGRES_PASSWORD: test2022
      POSTGRES_USER: test
      POSTGRES_DB: test_app
    ports:
      - 5433:5432
    networks:
      - growbase

  redis:
    image: redis
    container_name: 13ed-redis
    command: redis-server --requirepass growdev2022
    ports:
      - 6379:6379
    networks:
      - growbase

networks:
  growbase:
    driver: bridge

volumes:
  postgres:
